<!-- 
CREATE TABLE BOOKS (
  ID VARCHAR(5) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  WRITER VARCHAR(20) NOT NULL,
  PRICE DECIMAL(10,2) DEFAULT 0,
  GENRE VARCHAR(20) NOT NULL,
  PUBLISHER VARCHAR(20) NOT NULL,
  CNT DECIMAL(10,0) DEFAULT 0,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 
INSERT INTO BOOKS(
  ID,
  NAME,
  WRITER,
  PRICE,
  GENRE,
  PUBLISHER
) VALUES (
  'A1',
  '홍길동전',
  '허균',
  300,
  '소설',
  '허균 출판사'
)
 ON DUPLICATE KEY UPDATE
 CNT = CNT+1;
   
 INSERT INTO BOOKS(
  ID,
  NAME,
  WRITER,
  PRICE,
  GENRE,
  PUBLISHER
) VALUES (
  'B1',
  '레미제라블',
  '빅토르 위고',
  900,
  '소설',
  '빅토르 위고 출판사'
)
 ON DUPLICATE KEY UPDATE
 CNT = CNT+1;
  -->